"""Resumable creation of one neutral, evidence-rich task workspace."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from neurogolf.analysis.dossier import build_dossier
from neurogolf.analysis.report import write_analysis_artifacts
from neurogolf.arcgen.generator import GeneratorOracle
from neurogolf.arcgen.sampling import sample_many
from neurogolf.config.models import NeuroGolfSettings
from neurogolf.judge.registry import ChampionRegistry
from neurogolf.tasks.mapping import TaskMap
from neurogolf.tasks.principles import task_principle

TASK_AGENTS = """# Task-local NeuroGolf guidance

This workspace is exclusively for task {task_num:03d} / `{task_id}`. The root
`AGENTS.md` applies. Read `TASK_CONTEXT.md`, `analysis/`, canonical sources, and
`state/failure_packet.json` before changing the builder.

Open and inspect `analysis/examples.png` as an image in addition to reading the
text examples and dossier. Use the mapped ARC-GEN principle as a hypothesis,
not as a substitute for checking every input/output pair.

The ONNX lab helpers are optional and not universally opset-aware. The builder
accepts any positive opset, but each helper may implement only some operator
schema versions. Inspect helper/schema compatibility for the chosen opset and
validate with the full ONNX checker and ONNX Runtime. Use a version-correct
direct `onnx.helper` node when a lab helper is incompatible; do not force opset
12 just to fit a helper.

The current Kaggle leaderboard score is 8178.57, about 20.4465 points per task,
which implies a current approximate average objective/cost budget of 94.97
(intermediate tensor bytes plus parameter elements) per ONNX task graph. First
achieve complete correctness; then deliberately build and golf toward 94.97 or
lower without sacrificing generalization.

Editable: `solution/`, `devtests/`, and task-local analysis/state notes.
Protected: canonical data and generators, `utils/neurogolf_utils.py`, all
repository `neurogolf/judge/` files, integrity/sealed files, and champion state.
Never work on or launch another task from this directory. Run the external gate
instead of redefining acceptance. The parent orchestrator promotes only an exact
eligible passing hash; never invoke promotion or edit champion state directly.
"""

BUILD_TEMPLATE = '''"""Neutral builder template; replace with this task's inferred ONNX rule."""

from pathlib import Path

import onnx

from neurogolf.onnx_lab.templates import identity_model


def build() -> onnx.ModelProto:
    # Infrastructure-only neutral baseline. This is not a proposed task solution.
    return identity_model()


if __name__ == "__main__":
    destination = Path(__file__).with_name("candidate.onnx")
    model = build()
    onnx.checker.check_model(model, full_check=True)
    onnx.save(model, destination)
    print(destination)
'''

DEVTEST_TEMPLATE = '''"""Editable task-local development tests generated by `task prepare`."""

import importlib.util
import json
from pathlib import Path

import onnx
import pytest

from neurogolf.config import load_settings
from neurogolf.judge.candidate_runner import CandidateRunner
from neurogolf.judge.official_adapter import OfficialAdapter
from neurogolf.tasks.loader import load_kaggle_dataset
from neurogolf.tasks.mapping import TaskMap
from neurogolf.tasks.models import ArcExample

WORKSPACE = Path(__file__).resolve().parents[1]
TASK_NUM = {task_num}


def _build():
    path = WORKSPACE / "solution" / "build.py"
    spec = importlib.util.spec_from_file_location("task_builder", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.build()


def test_candidate_build_and_checker():
    model = _build()
    onnx.checker.check_model(model, full_check=True)


def test_data_and_generated_fixtures_are_well_formed():
    settings = load_settings()
    record = TaskMap(settings).get(TASK_NUM)
    dataset = load_kaggle_dataset(record.kaggle_json_path)
    assert dataset.train and dataset.test and dataset.arc_gen
    assert (WORKSPACE / "devtests" / "generated_examples.json").is_file()


def test_candidate_on_public_and_provided_arcgen(tmp_path: Path):
    # This deliberately fails for the neutral baseline until a semantic solution exists.
    settings = load_settings()
    adapter = OfficialAdapter(settings)
    record = TaskMap(settings).get(TASK_NUM)
    dataset = load_kaggle_dataset(record.kaggle_json_path)
    candidate = tmp_path / "candidate.onnx"
    onnx.save(_build(), candidate)
    runner = CandidateRunner(candidate, adapter)
    generated = json.loads((WORKSPACE / "devtests" / "generated_examples.json").read_text())
    generated_examples = [
        ArcExample(input=item["input"], output=item["output"]) for item in generated
    ]
    comparisons = runner.compare_many(
        [*dataset.train, *dataset.test, *dataset.arc_gen, *generated_examples],
        family="development",
    )
    assert comparisons and all(item.passed for item in comparisons)


def test_conversion_matches_official():
    settings = load_settings()
    adapter = OfficialAdapter(settings)
    example = load_kaggle_dataset(TaskMap(settings).get(TASK_NUM).kaggle_json_path).train[0]
    converted = adapter.convert_example(example)
    assert adapter.tensor_to_grid(converted["output"]) == example.output
'''


def _read_failures(workspace: Path) -> list[dict[str, Any]]:
    path = workspace / "state" / "failure_packet.json"
    if not path.is_file():
        return []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return [
            {
                "failure_count": payload.get("failure_count"),
                "failure_families": payload.get("failure_families"),
                "failure_signatures": payload.get("failure_signatures"),
            }
        ]
    except (OSError, json.JSONDecodeError):
        return [{"error": "existing failure packet is unreadable"}]


def _analysis_is_current(dossier_path: Path, *, principle: str) -> bool:
    if not dossier_path.is_file():
        return False
    try:
        payload = json.loads(dossier_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    return isinstance(payload, dict) and payload.get("arcgen_principle") == principle


def prepare_task(
    task_num: int,
    settings: NeuroGolfSettings,
    *,
    force: bool = False,
) -> dict[str, Any]:
    mapping = TaskMap(settings)
    record = mapping.get(task_num)
    workspace = settings.paths.task_workspace_root / f"task{task_num:03d}"
    analysis_dir = workspace / "analysis"
    devtests = workspace / "devtests"
    solution = workspace / "solution"
    state = workspace / "state"
    for directory in (analysis_dir, devtests, solution, state):
        directory.mkdir(parents=True, exist_ok=True)
    registry = ChampionRegistry(settings.paths.champion_root)
    champion = registry.current(task_num)
    principle = task_principle(settings.paths.repository_root, task_num, record.task_id)
    dossier_path = analysis_dir / "dossier.json"
    if force or not _analysis_is_current(dossier_path, principle=principle):
        dossier = build_dossier(
            record,
            settings,
            champion=champion.to_dict() if champion else None,
            failure_summaries=_read_failures(workspace),
        )
        artifacts = write_analysis_artifacts(
            dossier,
            record,
            analysis_dir,
            settings.paths.repository_root / "neurogolf/schemas/dossier.schema.json",
        )
    else:
        artifacts = {
            "dossier": dossier_path,
            "report": analysis_dir / "report.md",
            "text": analysis_dir / "examples.txt",
            "image": analysis_dir / "examples.png",
        }
    generated_path = devtests / "generated_examples.json"
    if force or not generated_path.is_file():
        oracle = GeneratorOracle(record, settings)
        samples = sample_many(
            oracle,
            count=min(8, settings.generation.development_seed_count),
            base_seed=137,
            namespace="task-dev-fixture-v1",
        )
        generated_path.write_text(
            json.dumps([item.model_dump(mode="json") for item in samples], indent=2) + "\n",
            encoding="utf-8",
        )
    files = {
        workspace / "AGENTS.md": TASK_AGENTS.format(task_num=task_num, task_id=record.task_id),
        solution / "build.py": BUILD_TEMPLATE,
        solution / "explanation.md": (
            f"# Task {task_num:03d} solution\n\n"
            "No semantic solution has been attempted. Replace the neutral identity baseline "
            "after analyzing the canonical evidence.\n"
        ),
        devtests / "test_solution.py": DEVTEST_TEMPLATE.format(task_num=task_num),
    }
    for path, content in files.items():
        if force or not path.exists():
            path.write_text(content, encoding="utf-8")
    context = {
        "task_num": task_num,
        "task_id": record.task_id,
        "arcgen_principle": principle,
        "workspace": str(workspace),
        "sources": record.model_dump(mode="json"),
        "current_champion": champion.to_dict() if champion else None,
        "commands": {
            "build": f"~/.venv/bin/python {solution / 'build.py'}",
            "devtests": f"~/.venv/bin/pytest -q {devtests}",
            "inspect": (
                "~/.venv/bin/python -m neurogolf.cli onnx inspect "
                f"{solution / 'candidate.onnx'} --cost-breakdown"
            ),
            "gate": (
                "~/.venv/bin/python -m neurogolf.cli gate run "
                f"--task {task_num} --candidate {solution / 'candidate.onnx'} "
                f"--output {state / 'gate_result.json'} --no-auto-promote"
            ),
        },
        "codex_result_schema": str(
            settings.paths.repository_root / "neurogolf/schemas/codex_result.schema.json"
        ),
    }
    context_path = workspace / "TASK_CONTEXT.md"
    context_path.write_text(
        f"# Task {task_num:03d} context\n\n```json\n{json.dumps(context, indent=2)}\n```\n",
        encoding="utf-8",
    )
    (state / "current_champion.json").write_text(
        json.dumps(champion.to_dict() if champion else None, indent=2) + "\n", encoding="utf-8"
    )
    return {
        "task_num": task_num,
        "task_id": record.task_id,
        "workspace": str(workspace),
        "analysis": {name: str(path) for name, path in artifacts.items()},
        "generated_examples": str(generated_path),
        "resumable": True,
    }


def prepare_all(settings: NeuroGolfSettings, *, force: bool = False) -> list[dict[str, Any]]:
    return [prepare_task(record.task_num, settings, force=force) for record in TaskMap(settings)]
