"""Editable task-local development tests generated by `task prepare`."""

import importlib.util
import json
from pathlib import Path

import onnx
import pytest

from neurogolf.config import load_settings
from neurogolf.judge.candidate_runner import CandidateRunner
from neurogolf.judge.official_adapter import OfficialAdapter
from neurogolf.onnx_lab.score_estimator import estimate_score
from neurogolf.tasks.loader import load_kaggle_dataset
from neurogolf.tasks.mapping import TaskMap
from neurogolf.tasks.models import ArcExample

WORKSPACE = Path(__file__).resolve().parents[1]
TASK_NUM = 1


def _build():
    path = WORKSPACE / "solution" / "build.py"
    spec = importlib.util.spec_from_file_location("task_builder", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.build()


def test_candidate_build_and_checker():
    model = _build()
    onnx.checker.check_model(model, full_check=True)


def test_candidate_retains_golfed_structure_and_cost():
    model = _build()
    assert [(item.domain, item.version) for item in model.opset_import] == [("", 9)]
    assert [node.op_type for node in model.graph.node] == [
        "Slice",
        "Add",
        "ConvTranspose",
        "ReduceMax",
        "Mul",
        "ConvTranspose",
    ]
    cost = estimate_score(model)
    assert cost["intermediate_tensor_bytes"] == 476
    assert cost["parameter_elements"] == 12
    assert cost["objective"] == 488


def test_data_and_generated_fixtures_are_well_formed():
    settings = load_settings()
    record = TaskMap(settings).get(TASK_NUM)
    dataset = load_kaggle_dataset(record.kaggle_json_path)
    assert dataset.train and dataset.test and dataset.arc_gen
    assert (WORKSPACE / "devtests" / "generated_examples.json").is_file()


def test_candidate_on_public_and_provided_arcgen(tmp_path: Path):
    settings = load_settings()
    adapter = OfficialAdapter(settings)
    record = TaskMap(settings).get(TASK_NUM)
    dataset = load_kaggle_dataset(record.kaggle_json_path)
    candidate = tmp_path / "candidate.onnx"
    onnx.save(_build(), candidate)
    runner = CandidateRunner(candidate, adapter)
    generated = json.loads((WORKSPACE / "devtests" / "generated_examples.json").read_text())
    generated_examples = [
        ArcExample(input=item["input"], output=item["output"]) for item in generated
    ]
    comparisons = runner.compare_many(
        [*dataset.train, *dataset.test, *dataset.arc_gen, *generated_examples],
        family="development",
    )
    assert comparisons and all(item.passed for item in comparisons)


def _kronecker_example(pattern: list[list[int]], color: int) -> ArcExample:
    input_grid = [[color if cell else 0 for cell in row] for row in pattern]
    output_grid = [
        [
            color if pattern[block_row][block_col] and pattern[inner_row][inner_col] else 0
            for block_col in range(3)
            for inner_col in range(3)
        ]
        for block_row in range(3)
        for inner_row in range(3)
    ]
    return ArcExample(input=input_grid, output=output_grid)


def test_candidate_on_semantic_boundaries_and_every_foreground_color(tmp_path: Path):
    patterns = [
        [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
        [[0, 0, 0], [0, 0, 0], [0, 0, 1]],
        [[0, 1, 0], [0, 0, 0], [1, 0, 1]],
        [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
    ]
    examples = [_kronecker_example(patterns[2], color) for color in range(1, 10)]
    examples.extend((_kronecker_example(patterns[0], 1), _kronecker_example(patterns[1], 2)))
    examples.append(_kronecker_example(patterns[3], 9))

    settings = load_settings()
    adapter = OfficialAdapter(settings)
    candidate = tmp_path / "candidate.onnx"
    onnx.save(_build(), candidate)
    comparisons = CandidateRunner(candidate, adapter).compare_many(
        examples, family="semantic-boundary"
    )
    assert comparisons and all(item.passed for item in comparisons)


def test_conversion_matches_official():
    settings = load_settings()
    adapter = OfficialAdapter(settings)
    example = load_kaggle_dataset(TaskMap(settings).get(TASK_NUM).kaggle_json_path).train[0]
    converted = adapter.convert_example(example)
    assert adapter.tensor_to_grid(converted["output"]) == example.output
